### ISSUE TITLE
Change color of menu and options text

### ISSUE THREAD

**Issue by peterennis** [sebaferreras/Ionic3-MultiLevelSideMenu#10]
I did the following expecting text to be yellow but it is still dark green,
i.e. the 'primary' color.

![capture165](https://user-images.githubusercontent.com/140737/30574080-81a6ac8a-9cac-11e7-87a1-15c6a3436d55.png)
![capture164](https://user-images.githubusercontent.com/140737/30574078-81a2b634-9cac-11e7-8362-62a80cfa7734.png)
![capture163](https://user-images.githubusercontent.com/140737/30574079-81a32d08-9cac-11e7-8de5-bcd23b921643.png)

**Comment by sebaferreras** [comment]
I think it may be related to a CSS specificity problem. Anyway, I've updated the component to add some classes to each type of option, so now it should be easier to change the styles. Please check the [`Theming`](https://github.com/sebaferreras/Ionic3-MultiLevelSideMenu#theming) section for more information.

I'll close this issue since this feature was added to the master branch, but feel free to re-open it if you need any help. Thanks :)
