### ISSUE TITLE
Permisos a items y subitems

### ISSUE THREAD

**Issue by matiasAS** [sebaferreras/Ionic3-MultiLevelSideMenu#14]
Hola Sebastián,
Me gustaría saber como podria agregarle un nuevo atributo a los items del menu, para que sean agregados o no dependiendo de un booleano correspondiente a si el usuario tiene o no permiso para acceder a una page en especifico. Yo ya tengo algo hecho te muestro codigo

`  {
          iconName: 'basket',
          displayName: 'Mis empresas',
          component: 'PgBusinessPage',
          permission: permissions.business.business,
        },`

eso corresponde a un subitem,

Por otro lado he modificado el método set del archivo side-menu-content:

`  @Input('options')
  set options(value: Array<MenuOptionModel>) {
    console.log("SET OPTIONS SIDE MENU")
    console.log(value)
    if (value) {
      this.menuOptions = value;
      console.log(value)
      if (!this.menuSettings || this.menuSettings.showSelectedOption) {
        this.selectedOption = this.menuOptions.find(option => option.selected);

        this.parents = new Map<string, MenuOptionModel>();

        this.menuOptions.forEach(option => {
          if (option.subItems) {
            option.subItems.forEach(subItem => {
              console.log("tiene permiso:", subItem.displayName, subItem.permission)
              if (subItem.permission) {
                console.log("agrego el item porque tiene permiso")
                console.log(option)
                this.parents.set(subItem.displayName.toLowerCase(), option);
              }else{
                console.log("no agrego porque no tiene permiso")
              }
            });
          }
        });
      }
    }
  }`

pensando que la linea:

` this.parents.set(subItem.displayName.toLowerCase(), option);` 

me agregaría o no el subitem pero no es así

espero que me puedas ayudar

Quedo atento

Matías Álvarez Sabaté

**Comment by sebaferreras** [comment]
Please write the description in English if possible, since it may help some other developers that don't speak Spanish :)

Instead of modifying the component to show/hide the options, add that logic in the `app.component.ts` file, and send only the options that should be shown to the `SideMenuComponent`. 

When you need to hide some of those options, update the property that you're binding to the `options` input of the component, and the shown options will be automatically updated

```
<side-menu-content 
    [options]="options" <! --  Update this property with the options that should be shown -->
    (selectOption)="selectOption($event)"
></side-menu-content>
```

So in your `app.component.ts` file you have an `options` property (where you initialize all the options of the side menu). If you need to show/hide some of those options, update the `options` property so it references a new array with only the options that you want to show in the side menu. After doing that, since the component uses `ChangeDetectionStrategy.OnPush`, the options being shown will be automatically updated.

I'll close this issue since it's not actually an issue with the component itself but a question about how component's communication works in Angular.
