### ISSUE TITLE
how to set a display name in menu using  a variable....

### ISSUE THREAD

**Issue by tejas008** [sebaferreras/Ionic3-MultiLevelSideMenu#24]
Thanks for your support all the way..I am trying to set a display name to menu using a variable...I am using ng2-translate ...as per selected language i want to set a display name.I am quiet confused or if i may using it in wrong way..but when i set the variable to display name it show nothing in side menu..please correct me ...its urgent.....thanks in advance 
This is my code
![capture 1](https://user-images.githubusercontent.com/34152354/33977940-6824b562-e0c3-11e7-80db-6acbe0b9f63a.PNG)

this code give me following output
![capture 2](https://user-images.githubusercontent.com/34152354/33977958-7a9ffc74-e0c3-11e7-8491-669032d0479f.PNG)

**Comment by sebaferreras** [comment]
What is the output of `console.log(res)`?

Anyway, I think that instead of doing things in that way, you can send the *translation key* as the `displayName` (would be "Dashboard" in your end, right?) and then add the `translate` pipe in the html code:

![translate](https://user-images.githubusercontent.com/17194770/33978180-b4a3bdae-e09e-11e7-8118-ce39a7ca1ff2.png)

Let me know if that works or we should handle it in a different way. 

Btw, I'll add support for ng2-translate soon :)

**Comment by phpweb** [comment]
I am also waiting for the ng2-translate support!

**Comment by sebaferreras** [comment]
I'll close this issue since using the `translate` pipe in the view should fix it for now until we add support for `ngx-translate`. Feel free to re-open it if you need any help.

Thanks :)
