### ISSUE TITLE
Restricting Side Menu From Collapsing.

### ISSUE THREAD

**Issue by Vickypr1902** [sebaferreras/Ionic3-MultiLevelSideMenu#31]
Hi,
I just wanted to know how can I restrict the side menu from closing when I navigate to another page...
Basically what I want is if anyone opens side-menu and then navigates to another page and when presses the back button I want the side-menu to be open as it was...
So how can I achieve this??
Thanks!

**Comment by sebaferreras** [comment]
If you don't want to **collapse the options** when closing the side menu, you'd need to remove the `(ionClose)="collapseMenuOptions()"` from the `app.html` file:

So that line instead of being like this:
`<ion-menu persistent="true" [content]="content" (ionClose)="collapseMenuOptions()">`
should be
`<ion-menu persistent="true" [content]="content">`


----
If you want to **keep the side menu opened**, you'd need to modify the method that handles what to do when an option is selected. So in the `app.component.ts` file, remove the `this.menuCtrl.close()` that closes the side menu:


```
public selectOption(option: MenuOptionModel): void {
    if (option.custom && option.custom.isLogin) {
        this.presentAlert('You\'ve clicked the login option!');
    } else if (option.custom && option.custom.isLogout) {
        this.presentAlert('You\'ve clicked the logout option!');
    } else if (option.custom && option.custom.isExternalLink) {
        let url = option.custom.externalUrl;
        window.open(url, '_blank');
    } else {
        // Redirect to the selected page
        this.navCtrl.setRoot(option.component || DetailsPage, { 'title': option.displayName });
    }
}
```

**Comment by Vickypr1902** [comment]
Hello,
First of all thanks for replying  Sebastián Ferreras, as you told I tried
the above modification but the issue here I get is the menu is open but the
page to which we navigates it goes below the menu so can't see any thing.
*I've attached a screenshot of the problem.*
*Thanks*
