### ISSUE TITLE
After restricting the side menu from closing the selected menu option page navigates but from below the side menu.

### ISSUE THREAD

**Issue by Vickypr1902** [sebaferreras/Ionic3-MultiLevelSideMenu#33]
As you can see the page navigates while the menu is open but the page navigates below the side menu.
How can I achieve opening of the page above the side menu while keeping the side menu open.
 [referring from previous issue](https://github.com/sebaferreras/Ionic3-MultiLevelSideMenu/issues/31#event-1566963157)

![screenshot 28](https://user-images.githubusercontent.com/37625636/38601022-de6c04ec-3d83-11e8-8b70-683f06ca8722.png)

**Comment by sebaferreras** [comment]
I'm afraid that it won't be possible to do that, since that's actually the default behavior of Ionic-Android. This component has nothing to do with the position of the side menu or the pages, that's just Ionic's default behavior:

![sidemenu](https://user-images.githubusercontent.com/17194770/38602768-03949b8e-3d6c-11e8-8463-c5f0055418cb.gif)

You may try to change the `z-index` of the entire menu, but I guess it will cause some other issues since it's not supposed to work like that.

**Comment by Vickypr1902** [comment]
Thanks a lot again.
Your work has helped a lot of people here, I appreciate your work.
Take care and have a nice day ahead 😊


Regards,
Ishwar Kumar Prasad

**Comment by sebaferreras** [comment]
Thank you for your kind words @Vickypr1902 , and thank you for opening issues with questions and improvements! 

Feel free to suggest any changes/improvements that you may need, and I'll do my best to add them to the component :)

Take care!
