### ISSUE TITLE
Custom component error

### ISSUE THREAD

**Issue by daVinci13** [sebaferreras/Ionic3-MultiLevelSideMenu#35]
I created a shared component and when I load it to my page i get:
`ERROR Error: Uncaught (in promise): RangeError: Maximum call stack size exceeded RangeError: Maximum call stack size exceeded`
and when I remove component import from my_page.module.ts everything is normal again.... 

accordion.ts:
![accordion ts](https://user-images.githubusercontent.com/4722244/39076299-d25b2916-44fa-11e8-8b27-70976fc56a14.png)

components.module.ts:
![components module](https://user-images.githubusercontent.com/4722244/39076304-d540ccf8-44fa-11e8-9d6b-b446f2372760.PNG)

my_page.module.ts:
![page module](https://user-images.githubusercontent.com/4722244/39076307-d70197ac-44fa-11e8-9389-c849b4b28548.PNG)

Error:
![error](https://user-images.githubusercontent.com/4722244/39076309-d8dc1dcc-44fa-11e8-9777-039d1721e443.PNG)

**Comment by sebaferreras** [comment]
I wouldn't know what could be wrong, since the code you posted seems to be ok. Is that a public repo that I can take a look at?

Still, this is not related to the `SideMenuContentComponent` so the **[Ionic forum](https://forum.ionicframework.com/)** or **[StackOverflow](https://stackoverflow.com/questions/tagged/ionic2+or+ionic3)** would be a better place for this question.

**Comment by daVinci13** [comment]
@sebaferreras I created a new component that should have some "accordion like cards" but I can't event get it to load simple "Hello world" text.... :/ Anyway thanks a lot for your help and keep up! :)

**Comment by sebaferreras** [comment]
Sorry to hear that @daVinci13. Feel free to create a **[StackBlitz demo](https://stackblitz.com/)** with your code and I'd try to help you out with that.
