### ISSUE TITLE
Example on how to use it step by step?

### ISSUE THREAD

**Issue by fahmisaad** [sebaferreras/Ionic3-MultiLevelSideMenu#41]
Hi, i'm new to ionic and i want to use your Multilevelsidemenu. but i dont know how to implement it. can someone provide me some links on how to use it?

**Comment by sebaferreras** [comment]
There's a **[section](https://github.com/sebaferreras/Ionic3-MultiLevelSideMenu#using-the-component-in-your-projects)** in the readme that explains how to use the component in any Ionic project.  You can also just download the demo and run it using first `npm install` and then `ionic serve` since this repo is a working Ionic app.

If you need some help related to Ionic and not this component, please go to **[Ionic docs](https://ionicframework.com/docs/)** or create a new thread in the **[Ionic forum](https://forum.ionicframework.com/)**.

**Comment by SamaludheenCignes** [comment]
How to include the SideMenuContentComponent in the declarations array from  @NgModule
