### ISSUE TITLE
Need method to set icon color for theming

### ISSUE THREAD

**Issue by peterennis** [sebaferreras/Ionic3-MultiLevelSideMenu#7]
I hard coded it, but this should be available in the scss?
![capture159](https://user-images.githubusercontent.com/140737/30530444-925548ea-9bfb-11e7-881d-ff3c4ddc6d46.png)
![capture160](https://user-images.githubusercontent.com/140737/30530449-9798f874-9bfb-11e7-9c10-daf9190ab076.png)

**Comment by sebaferreras** [comment]
Thanks for your feedback @peterennis. I'll be working on this enhancement today/tomorrow.

**Comment by sebaferreras** [comment]
This issue has been also fixed in the last commit, so please take a look at the [`Theming`](https://github.com/sebaferreras/Ionic3-MultiLevelSideMenu#theming) section for more details. You can now use the classes mentioned in that section, and target the `ion-icon` element to change the color of the icon.

I'll close this issue but feel free to re-open it if you need any help. Thanks :)
